name: Publish Python Packages to PyPI

on:
  push:
    tags:
      - 'v*'  # Push events matching v*, i.e. v1.0.4

jobs:
  build-and-publish:
    name: Build and publish Python üêç distributions üì¶ to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: python -m pip install --upgrade pip build

      - name: Build xoneaiagents
        working-directory: ./src/xoneai-agents
        run: python -m build

      - name: Build xoneai core
        working-directory: ./src/xoneai
        run: python -m build

      - name: Publish xoneaiagents to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./src/xoneai-agents/dist/
          skip-existing: true

      - name: Publish xoneai core to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./src/xoneai/dist/
          skip-existing: true
